[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "foundry-devops=lib/foundry-devops",
]
ffi = true

[fuzz]
runs = 128

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
